### PR TITLE
Wrong folder name

### PR DESCRIPTION
**Pull request by ziqianwenxuan**
the sentence in your program "from utlis.net_cfg_parser import parser_cfg_file" use the wrong folder name

the real folder name is utils

### CODE REVIEW

**Comment by wuxiaolianggit** [comment]
请问大神，您的数据格式具体格式是怎样的的呢？可以说明一下吗？
例如：'/home/tony/ocr/dataset/1516_3.jpg': [2384, 841, 2006, 1941, 949, 830, 625, 2574, 2574, 578, 233, 1126, 757, 2070, 659, 425, 1618, 842, 625, 2354, 1917, 736, 2561, 757]

**Comment by wuxiaolianggit** [comment]
可以问一下，你的数据格式时什么样的吗？

**Comment by ZGuQing** [comment]
大佬，请问你用到的数据集是什么，能分享一下吗

**Comment by ZGuQing** [comment]
test_img_list = ['/home/tony/ocr/test_data/00023.jpg']  请问图片列表怎么是一个jpg文件。

**Comment by heboyong** [comment]
请问使用的是哪一个数据集

**Comment by Ann19941118** [comment]
there is wrong in test_CRNN, net_params has no key named "model_save_path", and the ckpt confuses me, could you make sense?

**Comment by heboyong** [comment]
yeah,

> there is wrong in test_CRNN, net_params has no key named "model_save_path", and the ckpt confuses me, could you make sense?

yeah. if you notice net.cfg you will find that the [net] don't have the parameter “model_save_path”，you should change  "model_save_path" to "model_load_path" in test_crnn.
But I have another question about dataset,do you know which dataset trained for this model

**Comment by sun6s** [comment]
I can't find a dataset trained for this model

**Comment by Zhang-O** [comment]
大神 跪求数据集

**Comment by ziqianwenxuan** [comment]
同求数据集




------------------ 原始邮件 ------------------
发件人: "Zhang"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 晚上9:20
收件人: "wangjinxile/ocr_TDR"<ocr_TDR@noreply.github.com>; 
抄送: "雨辰之晨"<316240451@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wangjinxile/ocr_TDR] Wrong folder name (#1)




大神 跪求数据集

**Comment by xiyangde** [comment]
您好，请问word_onehot里面的字对应的值是依据什么规则赋的？比如：‘象’：0  这里的0代表什么，如果我要扩充字体集怎么添加新的键值对？谢谢

**Comment by HIHIHAHEI** [comment]
想问数据集是什么

**Comment by HIHIHAHEI** [comment]
I want to ask about the CNN is vgg? or else？

**Comment by HIHIHAHEI** [comment]
> 
> 
> the sentence in your program "from utlis.net_cfg_parser import parser_cfg_file" use the wrong folder name
> 
> the real folder name is utils

do u know whether the cnn is vgg?

**Comment by zcswdt** [comment]
> 想问数据集是什么

请问你们有数据集了吗？我也想要一份数据集

**Comment by cainiaoqiuzhu** [comment]
> test_img_list = ['/home/tony/ocr/test_data/00023.jpg'] 请问图片列表怎么是一个jpg文件。

请问有遇到说batch_size不一致的情况吗？

**Comment by HelloWorldlry** [comment]
> there is wrong in test_CRNN, net_params has no key named "model_save_path", and the ckpt confuses me, could you make sense?

I have this problem too, did you solve it please?

**Comment by NoahXuHui** [comment]
> > test_img_list = ['/home/tony/ocr/test_data/00023.jpg'] 请问图片列表怎么是一个jpg文件。
> 
> 请问有遇到说batch_size不一致的情况吗？

我遇到了请问下你解决了吗

**Comment by momocat-aric** [comment]
I used my own data (written by myself ) and the images in samples folder to run the test_crnn. It can only recognize the images in samples folder, and cannot recognize my word, even if I write the same words with samples word.

**Comment by IronmanJay** [comment]
请问，您的tensorflow版本是多少啊？

**Comment by IronmanJay** [comment]
ValueError: not enough values to unpack (expected 2, got 0)，请问报这个错怎么解决啊？

**Pull request closed without merging**
